version: '3.7'

services:
  db:
    image: "postgres:9.6"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/frontend/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - backend
    command: npm start

volumes:
  pg_data: