# Generated by Django 3.0.4 on 2020-03-28 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('testy_type', models.CharField(choices=[('campus_board', 'Campus board'), ('hangboard', 'Hangboard')],
                                                default='hangboard', max_length=255, verbose_name='Level')),
                ('image',
                 models.ImageField(blank=True, help_text='Add image how exercise should look like', upload_to='',
                                   verbose_name='Image')),
                ('private', models.BooleanField(default=False,
                                                help_text="If True, test set will be visible only for "
                                                          "creator or creator's athletes")),
                ('description', models.TextField(blank=True, help_text='Write more details about exercise',
                                                 verbose_name='Description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('pro', 'Pro')],
                                           default='advanced', max_length=255, verbose_name='Level')),
                ('testy_type', models.CharField(choices=[('campus_board', 'Campus board'), ('hangboard', 'Hangboard')],
                                                default='hangboard', max_length=255, verbose_name='Level')),
                ('promoted',
                 models.BooleanField(default=False, help_text='If True, test set will be promoted on the website')),
                ('private', models.BooleanField(default=False,
                                                help_text="If True, test set will be visible only for "
                                                          "creator or creator's athletes")),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('exercise',
                 models.ManyToManyField(related_name='test_sets', to='tests.Exercise', verbose_name='Exercises')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampusExercise',
            fields=[
            ],
            options={
                'verbose_name': 'Campus Exercise',
                'verbose_name_plural': 'Campus Exercises',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests.exercise',),
        ),
        migrations.CreateModel(
            name='CampusTestSet',
            fields=[
            ],
            options={
                'verbose_name': 'Campus Test Set',
                'verbose_name_plural': 'Campus Test Sets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests.testset',),
        ),
        migrations.CreateModel(
            name='HangboardExercise',
            fields=[
            ],
            options={
                'verbose_name': 'Hangboard Exercise',
                'verbose_name_plural': 'Hangboard Exercises',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests.exercise',),
        ),
        migrations.CreateModel(
            name='HangboardTest',
            fields=[
            ],
            options={
                'verbose_name': 'Hangboard Test Set',
                'verbose_name_plural': 'Hangboard Test Sets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests.testset',),
        ),
    ]
