# Generated by Django 3.0.4 on 2020-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('campus_board', 'Campus board'), ('hangboard', 'Hangboard')], default='hangboard', max_length=255, verbose_name='Exercise type'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='test_type',
            field=models.CharField(choices=[('campus_board', 'Campus board'), ('hangboard', 'Hangboard')], default='hangboard', max_length=255, verbose_name='Test Type'),
        ),
    ]
