# Generated by Django 3.0.4 on 2020-03-25 19:18

import crimpit.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[crimpit.accounts.validators.validate_birth_date], verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admindata/images/users/%Y/%m/%d', verbose_name='Profile photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='start_climbing',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[crimpit.accounts.validators.validate_start_climbing], verbose_name='Start climbing - year'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('athlete', 'Athlete')], default='athlete', max_length=50, verbose_name='User type'),
        ),
    ]
