# Generated by Django 3.0.4 on 2020-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0001_initial'),
        ('accounts', '0002_auto_20200328_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tests',
            field=models.ManyToManyField(related_name='users', to='tests.TestSet', verbose_name='Collection of tests'),
        ),
    ]
